# Generated by Django 3.2 on 2022-05-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'FOUR')])),
                ('table_seats', models.SmallIntegerField()),
                ('table_status', models.CharField(choices=[('AVL', 'ACTIVE'), ('BKD', 'COMPLETE'), ('OFF', 'CANCELLED')], max_length=10)),
                ('table_date', models.DateField()),
                ('table_start', models.DateTimeField()),
                ('table_end', models.DateTimeField()),
            ],
        ),
    ]
