# Generated by Django 3.2 on 2022-05-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='table_no',
            field=models.IntegerField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'FOUR')], default=0),
        ),
    ]
