# Generated by Django 3.2 on 2022-05-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_tables_table_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='table_no',
            field=models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'FOUR')], default=0, max_length=5),
        ),
    ]
