# Generated by Django 3.2 on 2022-05-19 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20220518_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='table_status',
            field=models.CharField(choices=[('ACT', 'ACTIVE'), ('OFF', 'OFFLINE')], default='Active', max_length=10),
        ),
        migrations.CreateModel(
            name='TableAvail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_date', models.DateField()),
                ('table_start', models.TimeField()),
                ('table_end', models.TimeField()),
                ('table_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tables.tables')),
            ],
        ),
    ]
