# Generated by Django 3.2 on 2022-05-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('booking_start', models.DateTimeField()),
                ('booking_end', models.DateTimeField()),
                ('booking_created', models.DateField(auto_now_add=True)),
                ('booking_status', models.CharField(choices=[('ACT', 'ACTIVE'), ('COMP', 'COMPLETE'), ('CANC', 'CANCELLED'), ('CANC', 'CANCELLED'), ('NOSHO', 'NO_SHOW')], max_length=5)),
                ('table', models.CharField(max_length=10)),
                ('customer', models.CharField(max_length=10)),
                ('booked_by', models.CharField(max_length=10)),
            ],
        ),
    ]
