# Generated by Django 3.2 on 2022-05-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_tables_table_no'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='table',
        ),
        migrations.AddField(
            model_name='bookings',
            name='table_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tables.tables'),
            preserve_default=False,
        ),
    ]
