# Generated by Django 3.2 on 2022-05-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20220518_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='booking_date',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_status',
            field=models.CharField(choices=[('ACT', 'ACTIVE'), ('COMP', 'COMPLETE'), ('CANC', 'CANCELLED'), ('CANC', 'CANCELLED'), ('NOSHO', 'NO_SHOW')], default='Active', max_length=5),
        ),
    ]
